const fs = require('fs')
const path = require('path')

const srcDir = '\\\\servidor-fs\\homefolder$\\luisgfr\\Desktop\\Luís\\Controle financeiro antigravity\\react-app\\src'
const destAppDir = '\\\\servidor-fs\\homefolder$\\luisgfr\\Desktop\\Luís\\Controle financeiro antigravity\\react-app\\next-app\\src\\app'
const destSrcDir = '\\\\servidor-fs\\homefolder$\\luisgfr\\Desktop\\Luís\\Controle financeiro antigravity\\react-app\\next-app\\src'

function copyDir(src, dest) {
  if (!fs.existsSync(dest)) fs.mkdirSync(dest, { recursive: true })
  const entries = fs.readdirSync(src, { withFileTypes: true })
  for (let e of entries) {
    if (e.isDirectory()) copyDir(path.join(src, e.name), path.join(dest, e.name))
    else processFile(path.join(src, e.name), path.join(dest, e.name))
  }
}

function processFile(srcPath, destPath) {
  let content = fs.readFileSync(srcPath, 'utf8')
  const ext = path.extname(srcPath)

  if (ext === '.jsx' || ext === '.js') {
    // Must add "use client" for anything using React hooks or DOM
    if (content.includes('useState') || content.includes('useEffect') || content.includes('useRef') || content.includes('useMemo') || content.includes('onClick')) {
      content = '"use client";\n\n' + content
    }

    // Replace Navigate router
    content = content.replace(/from\s+['"]react-router-dom['"]/g, "from 'next/navigation'")
    content = content.replace(/useNavigate/g, "useRouter")
    content = content.replace(/import\s+\{.*NavLink.*\}\s+from\s+['"]next\/navigation['"]/, (match) => {
      return `import Link from 'next/link';\nimport { usePathname } from 'next/navigation';`
    })

    // Manual replacements for hooks and Links used in Sidebar
    if (srcPath.includes('Sidebar.jsx')) {
      content = content.replace(/NavLink/g, "Link")
      content = content.replace(/className=\{\(\{ isActive \}\) => 'nav-item' \+ \(isActive \? ' active' : ''\)\}/g, "className={`nav-item ${pathName === '$1' ? 'active' : ''}`}")
      const matchToHref = /\bto=/g
      content = content.replace(matchToHref, "href=")
      content = content.replace("export default function Sidebar() {", "export default function Sidebar() {\n    const pathName = usePathname();")
    }

    // Manual App routing handling
    if (srcPath.includes('App.jsx')) return // Skip
    if (srcPath.includes('main.jsx')) return // Skip
  }

  // Mapping Page components to Next app router
  if (srcPath.includes('DashboardPage.jsx')) destPath = path.join(destAppDir, 'page.jsx')
  else if (srcPath.includes('ChartsPage.jsx')) { fs.mkdirSync(path.join(destAppDir, 'charts'), { recursive: true }); destPath = path.join(destAppDir, 'charts', 'page.jsx') }
  else if (srcPath.includes('ProfilePage.jsx')) { fs.mkdirSync(path.join(destAppDir, 'profile'), { recursive: true }); destPath = path.join(destAppDir, 'profile', 'page.jsx') }
  else if (srcPath.includes('AdminPage.jsx')) { fs.mkdirSync(path.join(destAppDir, 'admin'), { recursive: true }); destPath = path.join(destAppDir, 'admin', 'page.jsx') }
  else if (srcPath.includes('LoginPage.jsx')) { fs.mkdirSync(path.join(destAppDir, 'login'), { recursive: true }); destPath = path.join(destAppDir, 'login', 'page.jsx') }

  // Convert to globals.css and import the Tailwind Next.js stuff
  if (srcPath.includes('index.css')) {
    destPath = path.join(destAppDir, 'globals.css')
    content = '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n' + content
  }

  fs.writeFileSync(destPath, content)
  console.log('Processed:', destPath)
}

// Ensure App dir layout matches
const layoutContent = `
import './globals.css'

export const metadata = {
  title: 'FinanceFlow | Controle Seus Gastos',
  description: 'Dashboard financeiro premium para controle de gastos, investimentos e salários.',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className="antialiased">
        {children}
      </body>
    </html>
  )
}
`

if (!fs.existsSync(destAppDir)) fs.mkdirSync(destAppDir, { recursive: true })
fs.writeFileSync(path.join(destAppDir, 'layout.jsx'), layoutContent)

// Delete layout.tsx and page.tsx and globals.css generated by create-next-app
const delFiles = ['layout.js', 'page.js', 'layout.tsx', 'page.tsx', 'globals.css', 'favicon.ico']
for (let f of delFiles) {
  try { fs.unlinkSync(path.join(destAppDir, f)) } catch (e) { }
}

copyDir(path.join(srcDir, 'components'), path.join(destSrcDir, 'components'))
copyDir(path.join(srcDir, 'hooks'), path.join(destSrcDir, 'hooks'))
copyDir(path.join(srcDir, 'lib'), path.join(destSrcDir, 'lib'))
copyDir(path.join(srcDir, 'pages'), path.join(destSrcDir, 'pages-temp'))

// Manually trigger processFile for pages and CSS to route correctly
fs.readdirSync(path.join(srcDir, 'pages')).forEach(file => processFile(path.join(srcDir, 'pages', file), ''))
processFile(path.join(srcDir, 'index.css'), '')

try { fs.rmSync(path.join(destSrcDir, 'pages-temp'), { recursive: true, force: true }) } catch (e) { }

console.log('Migration complete.')
